# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install .NET Framework 4.8 Developer Pack
      run: choco install netfx-4.8-devpack
      shell: cmd

    - name: Download and Install .NET Framework 4.0 Targeting Pack
      run: |
        curl -L -o netfx_40lp.exe https://download.microsoft.com/download/5/7/D/57D795BD-63E8-4FCF-B015-868C3E5D8F41/netfx_40lp.exe
        start /wait netfx_40lp.exe /quiet /norestart
      shell: cmd

    - name: Restore dependencies
      run: dotnet restore
      shell: cmd

    - name: Build
      run: dotnet build --no-restore
      shell: cmd

    - name: Test
      run: dotnet test --no-build --verbosity normal
      shell: cmd
